import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function DashboardLogin() {
    return(
        <div className="m-0 w-screen h-screen ">
        <Head>
        <title>ASPASP2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="w-screen h-screen bg-[url('public/form-bg-update1.1.svg')] bg-no-repeat bg-cover bg-center ">
      <div className="flex justify-center pt-24">
          <div className="my-24 text-4xl">
              <h1>Admin Dashboard</h1>
          </div>


          </div>
          <div className="flex items-center justify-center w-screen">
            <form className="content-center" method="POST" action="">
            <label htmlFor="name">User Name</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autoComplete="name"/> <br/> <br/>

            <label htmlFor="name">Password</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="password" autoComplete="name"/> <br/> <br/>

            

            <button className="border-2 bg-[#064c7a] text-gray-100 text-2xl p-2 px-[5rem] mt-5 rounded-xl"><Link href="/">Login</Link></button>
          </form>
          </div>
        </div>
        </div>
    )
}