import Head from 'next/head'

export default function Gmass() {
    return(
        <div className="m-0 w-screen h-screen ">
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="h-screen bg-[url('/aspasp_registration.png')] bg-no-repeat">
      <div className="flex justify-center">
          <div className="mt-10 mb-24 text-2xl text-white">
              <button className="italic bg-fuchsia-900 px-10 py-2 rounded-full absolute left-[33%] bottom-[5%] drop-shadow-[0_1rem_1.75rem_gray]">DELEGATES Click Here</button>
              <button className="italic bg-teal-600 px-10 py-2 rounded-full absolute left-[53.5%] bottom-[5%] drop-shadow-[0_1rem_1.75rem_gray]">STUDENTS Click Here</button>
              <button className="italic bg-yellow-500 px-10 py-2 rounded-full absolute left-[73%] bottom-[5%] drop-shadow-[0_1rem_1.75rem_gray]">PRESENTERS Click Here</button>
          </div>


        </div>
    </div>
    </div>
    )
}