import Head from 'next/head'
import Image from 'next/image'

export default function Payment() {
    return(
        <div className="m-0 w-screen h-screen ">
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="w-screen h-screen bg-[url('https://test.mnerdsdev.com/Form-bg.svg')] bg-no-repeat bg-cover bg-center ">
      <div className="flex justify-center">
          <div className="my-24 text-4xl">
              <h1>Complete Registration - Payment</h1>
          </div>
          </div>

          <div className="flex justify-center">
          <div className="flex justify-center w-1/3">
            <form className="content-center" method="POST" action="">
            <label for="name">Payment Options</label><br/> <br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="fpx" type="radio" autocomplete="name" required/>
            <label for="fpx" value=""> FPX Banking</label> <br/><br/>

            <input className="bg-gray-200 border-2 border-gray-500" id="debit" type="radio" autocomplete="name" required/>
            <label for="debit" value=""> Credit/Debit Card</label> <br/><br/>

            <label for="name">Name on Card</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autocomplete="name"/> <br/> <br/>

            <label for="name">Card Number</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autocomplete="name"/> <br/> <br/>

            <label for="name">Exp Date</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autocomplete="name"/> <br/> <br/>

            <label for="name">CVV</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autocomplete="name"/> <br/> <br/>

            <button className="border-2 bg-[#064c7a] text-gray-100 text-2xl p-2 px-[5rem] rounded-xl"><a href="/regpref">Register</a></button>
          </form>
          </div>
          </div>
        </div>
        </div>
    )
}