import Head from 'next/head'
import Image from 'next/image'

export default function Register() {
    return(
        <div className="m-0 w-screen h-screen ">
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="w-screen h-screen bg-[url('https://test.mnerdsdev.com/Form-bg.svg')] bg-no-repeat bg-cover bg-center ">
      <div className="flex justify-center">
          <div className="my-24 text-4xl">
              <h1>Participant Registration</h1>
          </div>


          </div>
          <div className="flex items-center justify-center w-screen">
            <form className="content-center" method="POST" action="">
            <label for="name">Full Name</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autocomplete="name"/> <br/> <br/>

            <label for="name">Email</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="email" autocomplete="name" required /> <br/> <br/>

            <label for="name">Contact Number</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autocomplete="name" required /> <br/> <br/>

            <br/> <br/>
            <div className="text-2xl">Emergency Contact Information</div><br/>
            <label for="name">Full Name</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autocomplete="name" required /> <br/> <br/>

            <label for="name">Email</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autocomplete="name" required /> <br/> <br/>

            <label for="name">Contact Number</label><br/>
            <input className="bg-gray-200 border-2 border-gray-500" id="name" type="text" autocomplete="name" required /> <br/> <br/>

            <button className="border-2 bg-[#064c7a] text-gray-100 text-2xl p-2 px-[6.25rem] rounded-xl"><a href="/regpref">Next</a></button>
          </form>
          </div>
        </div>
        </div>
    )
}